DSA/Search.java, DSA/SearchbyKrit.java
=> Added 2 Searching Techniques with code and example

DSA/MoveZerosToEndByAnurag0git.java
MoveZerosToEndByAnurag0git.java are added in DSA folder as mentioned in issue #1
=> MoveZerosToEndByAnurag0git.java

DSA/FindSecondMaximumByAnurag0git.java
FindSecondMaximumByAnurag0git.java are added in DSA folder as mentioned in issue #1
=> FindSecondMaximumByAnurag0git.java

DSA/DesignBrowserHistoryByManojith.cpp
Add code #2 
**Description:**
This PR adds the C++ code for Design Browser History problem with description of the problem along with example and implementation approach. 
**Changes:**
- Added the necessary code in DesignBrowserHistoryByManojith.cpp under DSA folder.
=> Add Design Browser History

BrowserHistoryByAnurag0git.java
solved issue #2 as mentioned by author
=> BrowserHistoryByAnurag0git.java

DSA/QueueByIshika1880.java
Description:
This pull request adds a new Java implementation of a queue data structure to the repository. The implementation uses a linked list to store elements and provides methods for common queue operations, including enqueue, dequeue, peek, isEmpty, and printQueue.
=> solved Queue Implementation #12

Frontend/ExpenseTrackerByShalini/index.html, Frontend/ExpenseTrackerByShalini/readme.md, Frontend/ExpenseTrackerByShalini/script.js, Frontend/ExpenseTrackerByShalini/style.css
https://github.com/user-attachments/assets/0d0bb553-bb6c-4157-8371-8e1a06682d7d
fixes #61 
@indrakishore kindly review it
=> Added Expense Tracker

DSA/BalancedParenthesesByVIsheshJain.java, DSA/balanced_parentheses.java
- Added `BalancedParentheses.java` to the DSA folder.
- The program checks if a given string of parentheses (including `{}`, `[]`, `()`) is balanced.
- Implemented using a stack data structure to ensure parentheses are properly opened and closed in correct order.
- Includes edge cases for empty strings and mismatched parentheses.
=> Add BalancedParentheses.java to DSA Folder

DSA/SudokuSolver.java, DSA/TowerofHanoi.java
**Tower of Hanoi Solution:**
Recursively solves the Tower of Hanoi problem.
Moves all disks from the source rod to the destination rod using the auxiliary rod, following the rules of the problem.
**Sudoku Solver:**
Solves any valid 9x9 Sudoku puzzle using backtracking.
Efficiently fills in empty cells while checking constraints for row, column, and subgrid consistency.
=> Added new Programs

DSA/BestTimeToBuyAndSellStockByMahi.java, DSA/MaximumDepthBinaryTreeByMahi.java, DSA/NextGreaterElement.java
I have implemented java code for calculating maximum depth of binary tree please review it
=> Implemented Java Code for Maximum Depth of Binary Tree

DSA/BestTimeToBuyAndSellStockByMahi.java, DSA/NextGreaterElement.java
I have write Next Greater Element solution in java
=>  issue -9 Solution for Next Greater Element

DSA/PlaindromeLinkedList.java
The PalindromeLinkedList class determines whether a singly linked list is a palindrome by comparing values from both ends of the list. It utilizes an ArrayList to store the node values for efficient comparison
=> Palindrome Linked List Solution in Java#42

DSA/DynamicProblems/KnapsackProblemByOm.java
KnapSack Problem is basically calculating the maximum profit gained in a given constraint.
=>  KnapsackProblemByOm.java

DSA/TopoLogicalSortByOm.java
Description:
Implemention of Topological Sorting in Directed Acyclic Graph.
=> TopoLogicalSortByOm.java

DSA/MiddleElementLinkedlistByOm.java
Description:
The problem is about finding the middle element in the linked list.
=>  MiddleElementLinkedlistByOm.java

DSA/Doublylinkedlistimplementationbyatr.java
Java implementation of the Doubly Linked List using separate functions for insertion, deletion, reversal, concatenation, and printing.
=> Added Doubly linked list implementation in java

DSA/missing_number.java
Problem Statement :
find the missing numbers in an integer array that contains numbers from 1 to a specified maximum value (e.g., 100). The array may have one or more missing numbers, and the goal is to identify and print all the missing numbers.
The approach used in this code involves the following steps:
BitSet Initialization:
A BitSet is initialized with the size equal to the maximum value (count).
The BitSet is used to keep track of the numbers present in the array.
Marking Present Numbers:
Iterate through the given array and mark the corresponding index in the BitSet as true for each number present in the array.
Identifying Missing Numbers:
Calculate the number of missing elements by subtracting the length of the array from the maximum value (count).
Iterate through the BitSet to …
=>  MissingNumberByRiya.java

DSA/Sorting/HeapSort.java
Created heap sort method in java with proper comments and validation in a new sorting folder
=> Created HeapSort.java

DSA/BookAllocationProblemBinarySearch.cpp
Book Allocation Problem using Binary Search,to  find the minimum possible value of the maximum number of pages assigned to  any student, such that: 
Each student gets at least one book.
The maximum number of pages assigned to a student is minimized.
=> Book allocation problem using Binary Search

DSA/TCS_CodeVita2k24/TCSmock1que1.java, DSA/TCS_CodeVita2k24/TCSmock1que2.java, DSA/TCS_CodeVita2k24/TCSmock1que3.java, DSA/TCS_CodeVita2k24/TCSmock1que4.java, DSA/TCS_CodeVita2k24/TCSmock1que5.java, DSA/TCS_CodeVita2k24/TCSmock1que6.java
There was Mock test 1 held under TCS COde-vita 2024. I have added those questions and solutions to few of them under Developers-Community/DSA/TCS folder. It would be helpful for peers to practice this.
=> TCSmock1ByAnurag0git

ToDoAppSpuskar/Main.java, ToDoAppSpuskar/Task.java, ToDoAppSpuskar/TaskManager.java
A basic Java console-based To-Do list application that allows users to manage tasks using **CRUD operations**. You can add, edit, delete, view, and mark tasks as completed. This project is beginner-friendly and is perfect for learning **Java OOP** concepts.
- Add new tasks with title, description, and due date
- Edit existing tasks
- View all tasks
- Delete tasks
- Mark tasks as completed
- Java Development Kit (JDK) 8 or above
- A Java IDE (like IntelliJ IDEA or Eclipse) or a simple text editor
=> To-Do List App

Frontend/Landing Page Using Html and Css/index.html, Frontend/Landing Page Using Html and Css/styles.css
added landing page. kindly merge it
=> added landing page using html and css

DSA/BinaryTree/findDiameterofBinaryTreebycodeforlifeee.java
added DSA question of Binary Tree for finding its diameter with Full Detailed Approach along with Comments.
Please merge this File for Hacktoberfest 2024..Thankyou..
=> Issue : #131 : Added DSA Question findDiameterofBinaryTreebycodeforlifeee.java

DSA/BinaryTree/BinaryTreesB.java, DSA/BinaryTree/CountNodes.java, DSA/BinaryTree/Diameter.java, DSA/BinaryTree/HeightOfTree.java, DSA/BinaryTree/KthAncestor.java, DSA/BinaryTree/KthLevel.java, DSA/BinaryTree/LevelOrderTraversal.java, DSA/BinaryTree/LowestCommonAncestor.java, DSA/BinaryTree/MinimumDistance.java, DSA/BinaryTree/SubTree.java, DSA/BinaryTree/SumOfNodes.java, DSA/BinaryTree/TopViewTree.java, DSA/BinaryTree/TransformSum.java, DSA/Sorting/Insertionsort.java, DSA/Sorting/Quicksort.java
**Resolved the issue #114** 
Quick Sort Algorithm - QuickSort is a sorting algorithm based on the Divide and Conquer that picks an element as a pivot and partitions the given array around the picked pivot by placing the pivot in its correct position in the sorted array.
Time complexity of this Algorithm - O(nlogn)
Insertion Sort Algorithm - Insertion sort is a simple sorting algorithm that works by iteratively inserting each element of an unsorted list into its correct position in a sorted portion of the list. It is like sorting playing cards in your hands. You split the cards into two groups: the sorted cards and the unsorted cards. Then, you pick a card from the unsorted group and put it in the right place in the sorted group.
Time complexity of this Algorithm - O(N^2)
=> Added the code of Quick Sort and Insertion Sort Algorithms

DSA/linkedlist/LinkedListHeaderFile.h
@indrakishore https://github.com/indrakishore/Developers-Community/issues/93
I have created and added a header file which contains 6 neccessary functions of singly Linked List.
please approve and add level-2 tag I will add more functions
Here is outline :
=> #93 Linked list header file

DSA/0-1knapsack.java
The provided Java program implements the 0-1 Knapsack problem using dynamic programming to determine the maximum value that can be obtained with a given capacity. It defines a knapsack function that constructs a 2D array to track the maximum values for subsets of items based on their weights and values. The user is prompted to input the number of items, their respective weights and values, and the knapsack's capacity. After processing the inputs, the program calculates and outputs the maximum value achievable within the specified capacity. This approach efficiently solves the problem by building on previously computed results.
=> Created 0-1knapsack in java

DSA/RatInMaze.cpp
rat in maze problem in a 2D grid.
=> rat in maze prob

Frontend/Landing Page Using Html and Css/index.html, Frontend/Landing Page Using Html and Css/styles.css
1. Button Hover Effect Enhancement:
The button's hover effect was improved by adding a subtle shadow and a slight color change to enhance interactivity. This change makes the button more visually appealing and provides users with clear feedback when they hover over it, encouraging engagement.
2. Navbar Background Color Adjustment:
The navbar's background color was adjusted to a semi-transparent dark overlay to improve text readability against the background image. This adjustment ensures that the navigation links stand out, enhancing usability and providing a clearer path for users to navigate through the website.
=> one href link added

DSA/BinaryTree/VerticalOrderTraversal.java
=> added ./DSA/BinaryTree/VerticalOrderTraversal.java file

BellmanFord.c
=> BellmanFord.cByWasi

DSA/Graph/KruskalsAlgorithm.java, DSA/Graph/PrimsAlgorithm.java
implement Prim’s and Kruskal’s algorithms for finding the Minimum Spanning Tree (MST) in Java
=> Prim,s and Kruskal's algorithm
